
public class Main {

    public static void main(String[] args) {
        String sampleText = "THE SHORT HAIRED QUICK BROWN FOX COMES OUT OF IT'S CAGE AS IT JUMPS OVER THE LAZY DOG WHO LIES IN THE GRASS ASLEEP. I HOPE THIS TEST IS ABLE TO COVER ALL THAT NEEDS TO BE COVERED IN KEYSTROKE TESTING.";
        sampleText = "ATHLONE INSTITUTE OF TECHNOLOGY (AIT) HAS BEEN NAMED INSTITUTE OF TECHNOLOGY OF THE YEAR IN BOTH 2018 AND 2020." +
                " AIT IS THE LEADER IN THE INSTITUTE OF TECHNOLOGY SECTOR IN INNOVATION, APPLIED TEACHING AND STUDENT WELFARE. " +
                "A CORE STRENGTH OF AIT COMES FROM IDENTIFYING AREAS OF SKILLS SHORTAGE AND WORKING WITH BUSINESSES TO IMPROVE " +
                "LINKS BETWEEN ENTERPRISE AND ACADEMIA. THE INSTITUTE IS HOME TO 6,000 STUDENTS UNDERTAKING A BROAD RANGE OF " +
                "PROGRAMMES IN THE DOMAINS OF BUSINESS, HOSPITALITY, ENGINEERING, INFORMATICS, SCIENCE, HEALTH, SOCIAL SCIENCE " +
                "AND DESIGN. MORE THAN ONE TENTH OF THE FULL TIME STUDENT POPULATION COME FROM OVERSEAS WITH 63 NATIONALITIES " +
                "REPRESENTED, REFLECTING THE GLOBALISED NATURE OF ITS CAMPUS. THE INSTITUTE’S GLOBAL FOCUS IS ALSO EVIDENT IN THE " +
                "230 PARTNERSHIPS AND AGREEMENTS IT HAS SIGNED WITH UNIVERSITIES AND RESEARCH INSTITUTIONS AROUND THE WORLD.";
        Verifier verifier = new Verifier();
        System.out.println("IS VALID - "+verifier.validateParagraphText(sampleText));
    }


}
